
title: Naveen Resume
url: 'https://naveenkambham.github.io'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Naveen Kambham    
title: 'MACHINE LEARNING ENGINEER'  ## your title
location: Saskatoon , SK


# Social Profiles
facebook: https://www.facebook.com/kambhamnaveenkumar 
twitter: https://www.twitter.com/kambhamnaveen 
linkedin: https://www.linkedin.com/in/naveenkambham/  
github: https://www.github.com/naveenkambham  ## will change to github 
instagram: https://www.instagram.com/i.am.just.naveen_reddy  ## will change to instagram


# Update all the sections by editing the files inside _includes folder.
